{% set name = "collections-undo" %}
{% set version = "0.0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/collections-undo-{{ version }}.tar.gz
  sha256: 45429f7218b5f289e5dddce5c4834221dcf98b38f4803956a51e2bcdf2bfef6e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - python >=3.8
    - typing-extensions

test:
  imports:
    - collections_undo
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/collections-undo/
  summary: General undo/redo framework for Python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
