{% set name = "collections-undo" %}
{% set version = "0.0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/collections-undo-{{ version }}.tar.gz
  sha256: b161f628510f64fbe2889c35b397553320e6efe7dd106408d3b069affede3ac4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - python >=3.8
    - typing-extensions

test:
  imports:
    - collections_undo
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/hanjinliu/collections-undo
  summary: General undo/redo framework for Python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
